<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    <link rel="stylesheet" href="/css/candidates.css">
</head>
<body>
    <div class="container flex flex-col align-center">
        <h1>Error</h1>
        <main class="flex flex-col align-center">
            <div class="card">
                <p>${message}</p>
            </div>
            <a class="back flex align-center" href="/">back to main</a>
        </main>
    </div>
</body>
</html>